"""Initial_migration

Revision ID: c3c1b473b153
Revises: 
Create Date: 2026-02-05 14:34:38.763873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3c1b473b153'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semesters', sa.Column('academic_year', sa.String(length=20), nullable=False))
    op.drop_column('semesters', 'name')
    op.drop_column('subjects', 'updated_at')
    op.drop_column('subjects', 'credits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('credits', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('subjects', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('semesters', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('semesters', 'academic_year')
    # ### end Alembic commands ###
